---
version: "3.7"
name: netgpt
services:
  cache:
    domainname: cache.localhost
    image: redis
    expose:
      - "6379"
    networks:
      - backend
  auth:
    # The Authentication service is keycloak, by default.
    # When deployed with docker-compose, it is started in dev mode
    domainname: auth.localhost
    image: quay.io/keycloak/keycloak
    command:
      - "start-dev" # Change this to "start" to run in production mode
      - "--https-port=8443"
      - "--https-certificate-file=/etc/x509/https/tls.crt"
      - "--https-certificate-key-file=/etc/x509/https/tls.key"
    environment:
      - KEYCLOAK_ADMIN=admin # Change this to your desired admin username
      - KEYCLOAK_ADMIN_PASSWORD=keycloak # Change this to your desired admin password
    volumes:
      - ./certs/auth.key:/etc/x509/https/tls.key
      - ./certs/auth.crt:/etc/x509/https/tls.crt
    ports:
      - "7443:8443"
    networks:
      - frontend
  webui:
    domainname: www.localhost
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./certs/www.key:/etc/nginx/certs/certificate.key
      - ./certs/www.crt:/etc/nginx/certs/certificate.crt
    depends_on:
      - api
    x-develop:
      watch:
        - action: rebuild
          path: ./www
    networks:
      - frontend
  api:
    domainname: api.localhost
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "49488:49488"
    environment:
      - REDIS_HOST=cache.localhost
      - REDIS_PORT=6379
    volumes:
      - ./certs/api.key:/app/certs/api.key
      - ./certs/api.crt:/app/certs/api.crt
    depends_on:
      - auth
      - cache
    x-develop:
      watch:
        - action: rebuild
          path: ./api
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge



          